### PR TITLE
Add config.sh for challenge-response packages

### PR DESCRIPTION
**Pull request by prakashsurya**

### CODE REVIEW

**Comment by prakashsurya** [comment]
`pre-push` is [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/userland/job/pre-push/133/)

**Comment by pzakha** [comment]
@sebroy FYI github allows you to do a "Rebase and Merge" when merging PRs, which makes for less branching and a cleaner history.

**Comment by prakashsurya** [comment]
> which makes for less branching and a cleaner history.

Just FYI.. there's always the `--no-merges` options to `git-log`, if you'd prefer not to see the merge commits.

**Comment by pzakha** [comment]
Interesting, I didn't know about that option. That definitely helps somewhat.

**Pull request merged**
