### PR TITLE
TOOL-19394 Remove branch.config from linux-pkg to allow pre-gitflow implementation

### PR DESCRIPTION
**Pull request by palash-gandhi**
<details open>
<summary><h2> Problem </h2></summary>
</details>
The plan for the branch rename project is to create the pre-gitflow branches 
preemptively to allow testing.
The linux-pkg repo has a file in each production branch of the repo
that contains the name of the branch. Most callers of scripts in this repo
set a `DEFAULT_GIT_BRANCH` environment variable that is consumed
by these scripts to determine the branch to operate on.

Here are some of these callers:
https://github.com/delphix/devops-gate/blob/main/jenkins/jobs/pipelines/linux_pkg_build.groovy#L29
https://github.com/delphix/devops-gate/blob/main/jenkins/jobs/pipelines/linux_pkg_build_package.groovy#L45
https://github.com/delphix/devops-gate/blob/main/jenkins/jobs/pipelines/linux_pkg_check_updates.groovy#L26

The plan for the branch rename project is to create mirrored branches i.e. `develop` to be a mirror of `6.0/stage`
and so on. To avoid having branch-specific information in the branch, this change proposes to remove this file since
most of the consumers of this repo set this env var.

<details open>
<summary><h2> Solution </h2></summary>
Remove the file and all consumers of it.

git-utils change: https://github.com/delphix/git-utils/pull/77
</details>

<details open>
<summary><h2> Testing Done </h2></summary>

generate-jobs: http://ops.jenkins-palashgandhi.dcol2.delphix.com/job/generate-jobs/23/

build-packages: http://ops.jenkins-palashgandhi.dcol2.delphix.com/job/linux-pkg/job/6.0/job/stage/job/build-packages/job/pre-push/2/
</details>

### CODE REVIEW

**Comment by sebroy** [comment]
A couple of questions:
1. What is the failure mode if `DEFAULT_GIT_BRANCH` isn't set?
2. What should `DEFAULT_GIT_BRANCH` be set to if we're building a project branch, for example? Should it be set to the name of the project branch, or the name of the "product" tracking branch?

**Comment by palash-gandhi** [comment]
> A couple of questions:
> 
> 1. What is the failure mode if `DEFAULT_GIT_BRANCH` isn't set?
> 2. What should `DEFAULT_GIT_BRANCH` be set to if we're building a project branch, for example? Should it be set to the name of the project branch, or the name of the "product" tracking branch?

1. I added some checks to verify that DEFAULT_GIT_BRANCH is always set where required.
2. As far as I understand, `DEFAULT_GIT_BRANCH` should always be set to the "product" tracking branch. Unless the project branch exists across all package repos including linux-pkg.
From the README:
  >The product branch is used in multiple instances. When
  running [setup.sh](#setupsh), it will determine what linux-package-mirror
  link to use when fetching packages from apt (although those links can be
  overridden via DELPHIX_PACKAGE_MIRROR_MAIN and
  DELPHIX_PACKAGE_MIRROR_SECONDARY). When running [buildpkg.sh](#buildpkgsh),
  it will determine which branch to fetch from the package's repository, unless
  it is overridden via `-b`; if the package has build-dependencies on other
  linux-pkg packages, those dependencies will be fetched from an S3 url that is
  versioned based on the product branch (although the package dependencies
  URLs can be overridden via package_S3_URL variables). Finally, when running
  [sync-with-upstream.sh](#sync-with-upstreamsh) or
  [push-merge.sh](#push-mergesh) it defines what branch of the package is
  being updated.

If your project branch is only in 1 package repo, linux-pkg seems to use this env var to determine where to fetch dependencies from.

**Comment by prakashsurya** [comment]
w.r.t. testing.. I think we should also try to build a package manually.. e.g.

1. clone `bootstrap-20-04` image
2. get your linux-pkg changes on onto that system
3. run `./setup.sh && ./buildpkg.sh <pkg>` and verify that works as expected

we should probably also verify `git-linux-pkg build` works as expected..

w.r.t. seb's question/comment about project branches.. yea, I _think_ the branch in question here is more about the "product branch", such that dependencies get pulled from the right place.. e.g. using the correct linux mirror, and dependent packages for the build, etc..

so.. if we have a "project branch" that needs a special branch of the linux mirror.. or has a branched version of a dependent package.. then I think it'd make sense to use the project branch name here.. but if it's just one package, I think it's supposed to point to the "product branch" name, e.g. 6.0/stage.

I think it'd be really neat if we could write all the dependency fetching logic to be more project branch aware, such that a project didn't have to take such an "all or nothing" approach.. e.g. maybe we have a project that didn't want to branch all packages, but did want to branch the linux package mirror.. I'm not sure we have a good way to support and test/build like that..

e.g. something like this could be useful for next-LTS projects, where we likely do want a whole new mirror, but might not need to change each package that we develop/build.. or maybe the pre-gitflow project as we move to a new "develop" branch.. to me, both of these projects should be considered a normal "project branch", and our tooling should support them, but I don't think we're really there yet (likely due to us always thinking about these cases as "special cases", and such not trying to write the tools in a way that support them)..

but that's all a bit of a tangent to this particular PR...

**Comment by palash-gandhi** [comment]
I did run the git-util and it runs `setup.sh` and `buildpkg.sh`. Did you still want me to run them by hand? 
```
$ git linux-pkg build -m pg-bootstrap-20-04.dlpxdc.co cloud-init
BUILD MACHINE: pg-bootstrap-20-04.dlpxdc.co
Initializing linux-pkg on pg-bootstrap-20-04.dlpxdc.co ...
+ [[ ! -d linux-pkg ]]
+ git clone --branch 6.0/stage https://github.com/delphix/linux-pkg.git linux-pkg
Cloning into 'linux-pkg'...
+ cd linux-pkg
+ git show-ref -q refs/hidden/git-linux-pkg
+ git update-ref refs/hidden/git-linux-pkg HEAD
done.
Pushing HEAD to pg-bootstrap-20-04.dlpxdc.co ...
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To ssh://pg-bootstrap-20-04.dlpxdc.co/home/ubuntu/linux-pkg
   7bcef20..c7939f9  HEAD -> refs/hidden/git-linux-pkg
done.
+ export FORCE_COLORS=true
+ FORCE_COLORS=true
+ [[ -n '' ]]
+ cd linux-pkg
+ git checkout -q refs/hidden/git-linux-pkg
+ [[ -f packages/cloud-init/config.sh ]]
+ export DEFAULT_GIT_BRANCH=6.0/stage
+ DEFAULT_GIT_BRANCH=6.0/stage
+ ./setup.sh
Running: check_running_system
Running: configure_apt_sources
Running: sudo rm -rf /etc/apt/sources.list.d
Running: sudo apt-key add /home/ubuntu/linux-pkg/resources/delphix-secondary-mirror.key
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
Running: sudo apt-get update
Get:1 http://linux-package-mirror.delphix.com/6.0/stage/0caedb86/ubuntu focal InRelease [265 kB]
...
...
...
...
...
+ ./buildpkg.sh -r delphix-2023.02.13.16.59.16 cloud-init
Running: check_running_system
Running: run_setup_if_needed
Running: check_package_exists cloud-init

====================================================================
                     PACKAGE cloud-init
====================================================================
...
...
...
...
...
...
PACKAGE cloud-init: STAGE build COMPLETED in 62 seconds


PACKAGE cloud-init: STAGE store_build_info STARTED
~/linux-pkg/packages/cloud-init/tmp/repo ~/linux-pkg/packages/cloud-init/tmp
Running: cd /home/ubuntu/linux-pkg/packages/cloud-init/tmp
Running: store_build_info
Running: store_git_info
Running: pushd /home/ubuntu/linux-pkg/packages/cloud-init/tmp/repo
~/linux-pkg/packages/cloud-init/tmp
Running: popd
Running: cp /home/ubuntu/linux-pkg/PACKAGE_MIRROR_URL_MAIN /home/ubuntu/linux-pkg/packages/cloud-init/tmp/artifacts/
Running: cp /home/ubuntu/linux-pkg/PACKAGE_MIRROR_URL_SECONDARY /home/ubuntu/linux-pkg/packages/cloud-init/tmp/artifacts/
PACKAGE cloud-init: STAGE store_build_info COMPLETED in 0 seconds

Running: cd /home/ubuntu/linux-pkg/packages/cloud-init/tmp

PACKAGE cloud-init: STAGE post_build_checks STARTED
Running: dpkg-deb -c cloud-init_22.4.2-delphix-2023.02.13.16.59.16_all.deb | grep '/usr/share/doc/' | grep copyright
Running: post_build_checks
-rw-r--r-- root/root      1630 2023-02-14 01:00 ./usr/share/doc/cloud-init/copyright
PACKAGE cloud-init: STAGE post_build_checks COMPLETED in 0 seconds

Success: Package cloud-init has been built successfully.
Build products are in /home/ubuntu/linux-pkg/packages/cloud-init/tmp/artifacts

git-linux-pkg build took 160 seconds
SUCCESS
```

**Comment by prakashsurya** [comment]
if you run it by hand, it should fail, right? the only benefit would be testing that it correctly fails, due to not knowing what the product branch is, since it wouldn't be there in the environment (unless you specify it manually, too).

I'm good as-is, though..

**Comment by prakashsurya** [comment]
that run doesn't seem to be using your version of linux-pkg, is it? I see this:
```
+ git clone --branch 6.0/stage https://github.com/delphix/linux-pkg.git linux-pkg
Cloning into 'linux-pkg'...
```

**Comment by palash-gandhi** [comment]
Good catch Prakash.

Here's the test you recommended:
Without DEFAULT_GIT_BRANCH
```
ubuntu@ip-10-110-234-237:~$ git clone --branch 6.0/stage https://github.com/pgandhi-delphix/linux-pkg
Cloning into 'linux-pkg'...
remote: Enumerating objects: 1924, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 1924 (delta 14), reused 16 (delta 5), pack-reused 1886
Receiving objects: 100% (1924/1924), 449.18 KiB | 9.17 MiB/s, done.
Resolving deltas: 100% (1055/1055), done.
ubuntu@ip-10-110-234-237:~$ cd linux-pkg/
ubuntu@ip-10-110-234-237:~/linux-pkg$ git branch
* 6.0/stage
ubuntu@ip-10-110-234-237:~/linux-pkg$ git log -1
commit c7939f968f3aa006c778d27ddcfac5c3e262a7a5 (HEAD -> 6.0/stage, origin/6.0/stage)
Author: Palash Gandhi <palash.gandhi@delphix.com>
Date:   Fri Feb 10 11:39:33 2023 -0800

    TOOL-19394 Remove branch.config from linux-pkg to allow pre-gitflow implementation

    PR URL: https://www.github.com/delphix/linux-pkg/pull/275
ubuntu@ip-10-110-234-237:~/linux-pkg$ ./setup.sh
Running: check_running_system
Error: check_env: DEFAULT_GIT_BRANCH must be non-empty

ubuntu@ip-10-110-234-237:~/linux-pkg$ ./buildpkg.sh cloud-init
Running: check_running_system
Running: run_setup_if_needed
Running: check_package_exists cloud-init
Error: check_env: DEFAULT_GIT_BRANCH must be non-empty
```

With DEFAULT_GIT_BRANCH:
```
ubuntu@ip-10-110-234-237:~/linux-pkg$ export DEFAULT_GIT_BRANCH=6.0/stage
ubuntu@ip-10-110-234-237:~/linux-pkg$ ./setup.sh
Running: check_running_system
Running: configure_apt_sources
Running: sudo apt-key add /home/ubuntu/linux-pkg/resources/delphix-secondary-mirror.key
OK
Running: sudo apt-get update
Get:1 http://linux-package-mirror.delphix.com/6.0/stage/4399e5bb/ubuntu focal InRelease [265 kB]
...
...
Running: add_swap
Running: git config --global user.email eng@delphix.com
Running: git config --global user.name Delphix Engineering
Running: sudo touch /run/linux-pkg-setup
ubuntu@ip-10-110-234-237:~/linux-pkg$ ./buildpkg.sh cloud-init
Running: check_running_system
Running: run_setup_if_needed
Running: check_package_exists cloud-init

====================================================================
                     PACKAGE cloud-init
====================================================================

Running: load_package_config cloud-init
...
...
------------------------------------------------------------
PACKAGE_GIT_URL:      https://github.com/delphix/cloud-init.git
PACKAGE_GIT_BRANCH:   6.0/stage
PACKAGE_REVISION:     delphix-2023.02.14.17
------------------------------------------------------------
...
...
Running: cd /home/ubuntu/linux-pkg/packages/cloud-init/tmp

PACKAGE cloud-init: STAGE post_build_checks STARTED
Running: post_build_checks
Running: dpkg-deb -c cloud-init_22.4.2-delphix-2023.02.14.17_all.deb | grep '/usr/share/doc/' | grep copyright
-rw-r--r-- root/root      1630 2023-02-14 17:05 ./usr/share/doc/cloud-init/copyright
PACKAGE cloud-init: STAGE post_build_checks COMPLETED in 0 seconds

Success: Package cloud-init has been built successfully.
Build products are in /home/ubuntu/linux-pkg/packages/cloud-init/tmp/artifacts

ubuntu@ip-10-110-234-237:~/linux-pkg$
```

I also reran the git-util again and verified it works with my changes on the build machine:
```
$ git-linux-pkg build -m pg-bootstrap-20-04.dlpxdc.co cloud-init
BUILD MACHINE: pg-bootstrap-20-04.dlpxdc.co
Initializing linux-pkg on pg-bootstrap-20-04.dlpxdc.co ...
+ [[ ! -d linux-pkg ]]
+ cd linux-pkg
+ git show-ref -q refs/hidden/git-linux-pkg
+ git update-ref refs/hidden/git-linux-pkg HEAD
done.
Pushing HEAD to pg-bootstrap-20-04.dlpxdc.co ...
Everything up-to-date
done.
+ export FORCE_COLORS=true
+ FORCE_COLORS=true
+ [[ -n '' ]]
+ cd linux-pkg
+ git checkout -q refs/hidden/git-linux-pkg
+ [[ -f packages/cloud-init/config.sh ]]
+ export DEFAULT_GIT_BRANCH=6.0/stage
+ DEFAULT_GIT_BRANCH=6.0/stage
+ ./setup.sh
...
...
```

**Review by prakashsurya — APPROVED** [review]

**Comment by prakashsurya** [comment]
Also worth noting while we're on this topic.. this is a bit of a(nother) tagent.. but I'd personally advocate for moving the linux-pkg repository away from being versioned with the product, and instead make it more like the devops-gate, with just a main/master branch.

There's a couple things that are version specific in linux-pkg, that we'd need to think through.. like the list of packages to build, which can change from version to version.. but I think the bulk of this logic is version agnostic, and the build logic that needs to be version specific, can be done via conditionals, like we do in the devops-gate.. 

further, if we went that far, it might not even be necessary/ideal to have a separate linux-pkg repository.. e.g. maybe it would be better suited to just have these build scripts in the devops-gate.. (less sure about that, but just throwing that out there)..

again, just another tangent not directly related to this PR, but thoughts that come to mind, triggered by this PR.

**Comment by prakashsurya** [comment]
we might even want to consider moving the "linux-pkg config", that's specific to each package, into the repository that config belongs too.. e.g. maybe have each repository have a `.delphix/packaging` directory, that our build system consumes.. this way, there's less flag days.. if a repository wants to be built by linux-pkg, it would just create that directory and then we'd point our package system to the repository (e.g. maybe add it to a list, maintained in the devops-gate)..

I just feel like our current system is unnecessarily complicated for what we need.

**Comment by sebroy** [comment]
@prakashsurya we'd also have to deal with strange "meta" packages that have no associated source code repository (e.g. the adoptopenjdk and docker-python-image packages).

**Review by sebroy — APPROVED** [review]

**Comment by palash-gandhi** [comment]
Yeah, these are good ideas. Collecting and responding to them here for posterity:
>I think it'd be really neat if we could write all the dependency fetching logic to be more project branch aware, such that a project didn't have to take such an "all or nothing" approach.. e.g. maybe we have a project that didn't want to branch all packages, but did want to branch the linux package mirror.. I'm not sure we have a good way to support and test/build like that..

>e.g. something like this could be useful for next-LTS projects, where we likely do want a whole new mirror, but might not need to change each package that we develop/build.. or maybe the pre-gitflow project as we move to a new "develop" branch.. to me, both of these projects should be considered a normal "project branch", and our tooling should support them, but I don't think we're really there yet (likely due to us always thinking about these cases as "special cases", and such not trying to write the tools in a way that support them)..

>Also worth noting while we're on this topic.. this is a bit of a(nother) tagent.. but I'd personally advocate for moving the linux-pkg repository away from being versioned with the product, and instead make it more like the devops-gate, with just a main/master branch.

> There's a couple things that are version specific in linux-pkg, that we'd need to think through.. like the list of packages to build, which can change from version to version.. but I think the bulk of this logic is version agnostic, and the build logic that needs to be version specific, can be done via conditionals, like we do in the devops-gate..

> further, if we went that far, it might not even be necessary/ideal to have a separate linux-pkg repository.. e.g. maybe it would be better suited to just have these build scripts in the devops-gate.. (less sure about that, but just throwing that out there)..
>we might even want to consider moving the "linux-pkg config", that's specific to each package, into the repository that config belongs too.. e.g. maybe have each repository have a .delphix/packaging directory, that our build system consumes.. this way, there's less flag days.. if a repository wants to be built by linux-pkg, it would just create that directory and then we'd point our package system to the repository (e.g. maybe add it to a list, maintained in the devops-gate)..
I just feel like our current system is unnecessarily complicated for what we need.

**Comment by palash-gandhi** [comment]
@sebroy I see that docker-python-image does have a source code repo: https://github.com/delphix/docker-python-image
But adoptopenjdk does not. For my knowledge, does that imply that we only ever use a single version of adoptopenjdk in all our product branches? And if so, linux-pkg scripts shouldn't have to deal with them, just like they don't now, right?

**Comment by sebroy** [comment]
@pgandhi-delphix we do not, by virtue of the fact that linux-pkg is branched and versioned (with release tags) the same way as other product repos. That's the point I'm trying to make. In order to remove the package list and package build recipes out of linux-pkg, we'd have to somehow handle adoptopenjdk. (I was evidently mistaken about the docker one)...

**Comment by prakashsurya** [comment]
> does that imply that we only ever use a single version of adoptopenjdk in all our product branches?

no.. you can see the version is embedded in the config file:
```
case $(dpkg-architecture -q DEB_HOST_ARCH 2>/dev/null || echo "none") in
amd64)
        _tarfile="OpenJDK8U-jdk_x64_linux_hotspot_8u362b09.tar.gz"
        _tarfile_sha256="1486a792fb224611ce0cd0e83d4aacd3503b56698549f8e9a9f0a6ebb83bdba1"
        _jdk_path="/usr/lib/jvm/adoptopenjdk-java8-jdk-amd64"
        ;;
arm64)
        _tarfile="OpenJDK8U-jdk_aarch64_linux_hotspot_8u362b09.tar.gz"
        _tarfile_sha256="9290a8beefd7a94f0eb030f62d402411a852100482b9c5b63714bacc57002c2a"
        _jdk_path="/usr/lib/jvm/adoptopenjdk-java8-jdk-arm64"
        ;;
*) ;;
```
those variables can (and do) change for different releases..

**Comment by prakashsurya** [comment]
> we'd have to somehow handle adoptopenjdk.

yea, there'd be some work we need to figure out.. I didn't mean to imply it'd be "free".. but I think that's all stuff we could figure out, and we might wind up with a simpler solution in the end..

honestly, I haven't thought through all of this is detail.. but I have thought about it a little, when I've had to fight with it in the past. :p

**Comment by palash-gandhi** [comment]
Makes sense. For the record: putting the package lists in a file in the devops-gate will lead to an extra step in the release checklist of manually managing them on the day of CC. This is currently achieved in an automated fashion via branching the repo using the `merge-repos` script. There should be a better way to do this, like relying on the fact that the packages themselves branch and we source this information from the package branches as Prakash suggested.

**Comment by prakashsurya** [comment]
> we'd also have to deal with strange "meta" packages that have no associated source code repository

FWIW.. the fact that we don't have an actual "repository" for these, I'd argue, is a layering violation.. it was implemented this way because it was "easy", not necessarily because it was "correct"..

I think I'd advocate for these to actually become a "real" repository, where that repository basically was just a build script of some sort.. much like, what I did for our delphix-rust repository ([here](https://github.com/delphix/delphix-rust)), which isn't much more than a script that downloads a tarball and unpacks it.

**Pull request merged**
