### PR TITLE
Add dependency on "host-jdks" to "virtualization" package

### PR DESCRIPTION
**Pull request by aditya-joshi-delphix**
# Context:

all host-jdks changes together. host-jdks config.sh, virtualization config.sh and main.pkgs

# Testing:
http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/5240/console

### CODE REVIEW

**Comment by aditya-joshi-delphix** [comment]
@pzakha @matt-skinner-delphix

**Comment by pzakha** [comment]
LGTM, pending testing

**Comment by prakashsurya** [comment]
I kicked off build of this change, plus my in-progress host-jdks work (https://github.com/delphix/host-jdks/pull/3), plus @aditya-joshi-delphix 's in-progress app-gate changes.. see [here](http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg/job/custom/job/build-packages/job/custom/74/).

**Comment by aditya-joshi-delphix** [comment]
@pzakha

**Review by prakashsurya — APPROVED** [review]

**Review by pzakha — APPROVED** [review]
LGTM, pending testing.

FYI, I see that the `host-jdks` package has been built at http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg/job/master/job/build-package/job/host-jdks/job/post-push/, so this should be safe once testing passes.

**Comment by prakashsurya** [comment]
Here's a build of the `virtualization` package, with this change in place: [link](http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg/job/master/job/build-package/job/virtualization/job/pre-push/1)

@pzakha is this the testing you were looking for?

**Comment by prakashsurya** [comment]
I have not looked at those failures, but this change, in isolation, should not have any impact on the virtualization package or the product, as it's simply adding a build time dependency (that's currently unused), and nothing else.

The build you linked to, include the in-progress changes Aditya is working on for the app-gate, but those changes are not relevant for testing this specific PR.

As the changes to the app-gate are worked on, we can (and will) verify those changes with `git-ab-pre-push`, and land with `git-dx-test`, as we would any other app-gate change.

**Pull request merged**
