### PR TITLE
Upgrade jdk version to 8u302b08

### PR DESCRIPTION
**Pull request by smeda-delphix**
Upgrade JDK8 to the latest available version

# Testing
Manually verified the java version for VM from image created by http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6023/  
```
delphix@ip-10-110-220-219:~$ java -version
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.302-b08, mixed mode)
```
No failed tests in orchestrator run.

### CODE REVIEW

**Review by pzakha — APPROVED** [review]
Could you re-run the same test-run with REBUILD_DEPENDENCIES checked?
This will rebuild virtualization, masking and sso with this new package

**Comment by pzakha** [comment]
Also, as a reminder, once this is pushed we'll need to manually trigger the build of the `adoptopenjdk` package in ops.jenkins.

**Comment by smeda-delphix** [comment]
started a new run - http://selfservice.jenkins.delphix.com/job/devops-gate/job/master/job/appliance-build-orchestrator-pre-push/6033/

**Comment by smeda-delphix** [comment]
verified on the engine from new run. All looks good - 
```
delphix@ip-10-110-224-105:~$ java -version
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.302-b08, mixed mode)
```

**Review by rasantel — APPROVED** [review]

**Pull request merged**
